version: '3.8'

services:
  web:
    build: .
    command: python -m poetry run uvicorn src.main:app --host 0.0.0.0 --port 4000
    volumes:
      - .:/src
    ports:
      - 4000:4000
    depends_on:
      - postgres
    networks:
      - bound
  
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    networks:
      - bound

volumes:
  postgres_data:
networks:
  bound:
    driver: bridge